image: julia:0.6

before_script:
  - julia -e 'Pkg.clone(pwd())'

testjob:
  script:
    - julia -e 'Pkg.test("PhasedArray", coverage=true)'
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("PhasedArray"));
      using Coverage; cl, tl = get_summary(process_folder());
      println("(", cl/tl*100, "%) covered")'